
import turtle
ventana=turtle.Screen ()
ventana.bgcolor('white')
ventana.title('mi ventana')

rafael=turtle.Turtle()
rafael.shape('turtle')
rafael.color('blue')
rafael.pensize(2)
rafael.speed(1)

rafael.right(180)
rafael.right(90)
rafael.forward(60)
rafael.right(90)
rafael.forward(70)
rafael.right(90)
rafael.forward(80)
rafael.right(90)
rafael.forward(90)
rafael.right(90)
rafael.forward(100)
rafael.right(90)
rafael.forward(110)
rafael.right(90)
rafael.forward(120)
rafael.right(90)
rafael.forward(130)
rafael.right(90)
rafael.forward(140)
rafael.right(90)
rafael.forward(150)
rafael.right(90)
rafael.forward(160)
rafael.right(90)
rafael.forward(170)
rafael.right(90)
rafael.forward(180)
rafael.right(90)
rafael.forward(190)
rafael.right(90)
rafael.forward(110)
rafael.right(90)
rafael.forward(120)
rafael.right(90)
rafael.forward(130)
rafael.right(90)
rafael.forward(140)
rafael.right(90)
rafael.forward(150)
rafael.right(90)


rafael.penup()

ventana.mainloop()